application: getlevr
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  script: landing.app
- url: /phone.*
  script: phone.app
- url: /merchants.*
  script: merchants.app
- url: /new
  script: test_class.app
- url: /new_category
  script: populate_categories.app
- url: /login
  script: login.app
- url: /loginstate
  script: loginstate.app
- url: /logout
  script: logout.app
- url: /emptySet.*
  script: emptySet.app
- url: /admin.*
  script: admin.app
- url: /share.*
  script: share.app
- url: /payments/.*
  script: payments.app
- url: /test.*
  script: test.app
- url: /tasks/cleanDeals
  script: tasks/cleanDeals.py


- url: /img
  static_dir: img
- url: /css
  static_dir: css
- url: /js
  static_dir: js
  
libraries:
- name: jinja2
  version: latest
