application: getlevr
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  script: landing.app
- url: /phone
  script: phone.app
- url: /merchants/.*
  script: merchants.app
- url: /new
  script: test_class.app
- url: /get
  script: test_get.app
- url: /new_category
  script: populate_categories.app
- url: /img
  static_dir: img
- url: /css
  static_dir: css
  
libraries:
- name: jinja2
  version: latest