application: getlevr
version: 1
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /
  script: landing.app
- url: /phone.*
  script: phone.app
- url: /merchants.*
  script: merchants.app
- url: /new.*
  script: test_class.app
  login: admin
- url: /login
  script: login.app
- url: /loginstate
  script: loginstate.app
- url: /logout
  script: logout.app
- url: /emptySet.*
  script: emptySet.app
  login: admin
  secure: always
- url: /admin.*
  script: admin.app
  login: admin
  secure: always
- url: /share.*
  script: share.app
- url: /payments/.*
  script: payments.app
  login: admin
  secure: always
- url: /test.*
  script: test.py
  login: admin
- url: /tasks/cleanDeals
  script: cleanDeals.py
  login: admin
<<<<<<< HEAD
- url: /sandbox
  script: test.app
  login: admin
- url: /password.*
  script: password.app
=======
- url: /sandbox/.*
  script: sandbox.app
>>>>>>> blob



- url: /img
  static_dir: img
- url: /css
  static_dir: css
- url: /js
  static_dir: js
  
libraries:
- name: jinja2
  version: latest
- name: pycrypto
  version: 2.3

builtins:
- appstats: on
